frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

portada:
    path:   /portada
    defaults: { _controller: FrontendBundle:Default:portada }
    

